### ISSUE TITLE
Delete value

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic-storage#35] opened 2016-10-30 23:01 UTC
How do I delete a certain key => value pair with this? key => null???

**Comment by mlynch** [comment] 2016-10-31 17:23
Hey, this isn't really an issue per say so I'm closing this for now. If you have more code to share perhaps someone can help! Thanks.

**Closed by mlynch** 2016-10-31 17:23 UTC

**Comment by EralpB** [comment] 2016-11-17 10:39
Wow README doesn't say how to delete a value, and this issue has been closed.

The issue is there's no code example on how to delete a key. Is there a method? Shall I set to null or undefined?

**Comment by mlynch** [comment] 2016-11-17 14:36
Just updated the README, but for others, use `Storage.remove(key)`
