### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AlexandruCiobanu** [driftyco/ionic-storage#2] opened 2016-09-29 06:56 UTC
I get a weird error trying to install it. This happened when I tried to create a sidemanu app in the new ionic. Below I tried specifically installing it but got this:
```
>npm install @ionic/storage
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  driftyco/localforage-cordovasqlitedriver#9803562a61c2172a69f3475f97e98922c0b49ac0 resetting remote C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-adc44a49771a5261e0152969fa2f1be9 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-adc44a49771a5261e0152969fa2f1be9: Cloning into bare repository 'C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-adc44a49771a5261e0152969fa2f1be9'...
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-adc44a49771a5261e0152969fa2f1be9:
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-adc44a49771a5261e0152969fa2f1be9: fatal: unable to overwrite old ref-pack file: Is a directory
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  driftyco/localforage-cordovasqlitedriver#9803562a61c2172a69f3475f97e98922c0b49ac0 resetting remote C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-dcf0e8319b4cf3f9b06a408e9fc38b35 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-dcf0e8319b4cf3f9b06a408e9fc38b35: Cloning into bare repository 'C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-dcf0e8319b4cf3f9b06a408e9fc38b35'...
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-dcf0e8319b4cf3f9b06a408e9fc38b35:
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-dcf0e8319b4cf3f9b06a408e9fc38b35: fatal: Fetch attempted without a local repo
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  driftyco/localforage-cordovasqlitedriver#9803562a61c2172a69f3475f97e98922c0b49ac0 resetting remote C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692: Cloning into bare repository 'C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692'...
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692:
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692: fatal: The remote end hung up unexpectedly
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@ionic/storage"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.git C:\Users\Eu\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-4579512e1b145fa41359e3b52a372692
npm ERR! Permission denied (publickey).
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Business\upwork\RyanSchefke\mobilitEASE\npm-debug.log
```

**Comment by AlexandruCiobanu** [comment] 2016-09-29 07:16
INstalling:
```
npm install https://github.com/driftyco/localForage-cordovaSQLiteDriver.git
```
works

**Comment by mlynch** [comment] 2016-09-29 20:59
Hey @AlexandruCiobanu, this error seems to indicate either a lack of drive space or a permission issue locally. What version of npm?

**Comment by mlynch** [comment] 2016-09-30 23:45
Closing as I'm not able to reproduce and it looks like an npm or other local issue unrelated to this plugin.

**Closed by mlynch** 2016-09-30 23:45 UTC
