### ISSUE TITLE
npm install @ionic/storage is not working

### ISSUE THREAD

**Issue by PrithiviRajG** [driftyco/ionic-storage#9] opened 2016-10-03 12:52 UTC
I am not able to run this command to install ionic storage
PFA the exception

[npm-debug.txt](https://github.com/driftyco/ionic-storage/files/506246/npm-debug.txt)

**Comment by mlynch** [comment] 2016-10-11 19:23
Can you try 1.1.6? Closing as a duplicate of #12

**Closed by mlynch** 2016-10-11 19:23 UTC
